FROM python:3.11-slim-bookworm as development_build

ARG YOUR_ENV

ENV YOUR_ENV=${YOUR_ENV} \
    PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=random \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    # Poetry's configuration:
    PDM_CHECK_UPDATE=false

# System deps:
# RUN curl -sSL https://install.python-poetry.org | python3 -

# Copy only requirements to cache them in docker layer
WORKDIR /code
RUN pip install pdm
COPY ./pdm.lock ./pyproject.toml README.md /code/

# Project initialization:
RUN pdm install -G:all

# Creating folders, and files for a project:
COPY . /code