version: "3.3"

volumes:
  db_data:

services:
  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 10s
      retries: 5
    restart: always

  tests:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.test
    command:
      [
        "pytest",
        "./tests",
        "--cov-report",
        "xml",
        "--cov-fail-under",
        "60",
        "--cov",
      ]
    depends_on:
      db:
        condition: service_healthy
    environment:
      - IS_DOCKER_TEST=yes
