name: Python package

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      poetry-version:
        required: false
        type: string
        default: "1.8"
      coverage:
        required: false
        type: boolean
        default: false
      os:
        required: false
        type: string
        default: "ubuntu-latest"
      timeout:
        required: false
        type: number
        default: 60


jobs:
  test:
    timeout-minutes: ${{ inputs.timeout }}
    runs-on: ${{ inputs.os }}
    defaults:
      run:
        shell: bash
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ inputs.python-version }}
      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('pdm.lock') }}
      - name: Install the project dependencies
        run: make install
      - name: Run the automated tests with coverage
        if: ${{ inputs.coverage }}
        run: make test